GET http://localhost:5293

###
GET http://localhost:5293/games

###
GET http://localhost:5293/games/5

###
POST http://localhost:5293/games
Content-Type: application/json

{
    "name": "PUBG pc",
    "genre": "Action shooter",
    "price": 20.11,
    "releaseDate": "2019-10-20"
}

###
PUT http://localhost:5293/games/1
Content-Type: application/json

{
    "name": "Street Fighter 6",
    "genre": "Action",
    "price": 50.33,
    "releaseDate": "2023-06-02"
}

###
DELETE http://localhost:5293/games/5
